In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
df = pd.read_csv("C:\\Users\\om sai compurer1\\Desktop\\used car\\CAR DETAILS FROM CAR DEKHO.csv")

In [3]:
df

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner
...,...,...,...,...,...,...,...,...
4335,Hyundai i20 Magna 1.4 CRDi (Diesel),2014,409999,80000,Diesel,Individual,Manual,Second Owner
4336,Hyundai i20 Magna 1.4 CRDi,2014,409999,80000,Diesel,Individual,Manual,Second Owner
4337,Maruti 800 AC BSIII,2009,110000,83000,Petrol,Individual,Manual,Second Owner
4338,Hyundai Creta 1.6 CRDi SX Option,2016,865000,90000,Diesel,Individual,Manual,First Owner
4339,Renault KWID RXT,2016,225000,40000,Petrol,Individual,Manual,First Owner

In [4]:
df["fuel"].unique()

<StringArray>
['Petrol', 'Diesel', 'CNG', 'LPG', 'Electric']
Length: 5, dtype: str

In [5]:
fuel ={
    "Petrol": 0,
    "Diesel": 1,
    "CNG": 2,
    "LPG": 3,
    "Electric": 4,
}

In [6]:
df["fuel"]=df["fuel"].map(fuel)

In [7]:
df["seller_type"].unique()

<StringArray>
['Individual', 'Dealer', 'Trustmark Dealer']
Length: 3, dtype: str

In [8]:
seller_type = {
    "Individual": 0,
    "Dealer": 1,
    "Trustmark Dealer": 2
}

In [9]:
df["seller_type"]=df["seller_type"].map(seller_type)

In [10]:
df["transmission"].unique()
transmission = {
    "Manual": 0,
    "Automatic": 1,
}
df["transmission"]=df["transmission"].map(transmission)
df

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,0,0,0,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,0,0,0,First Owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,1,0,0,First Owner
3,Datsun RediGO T Option,2017,250000,46000,0,0,0,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,1,0,0,Second Owner
...,...,...,...,...,...,...,...,...
4335,Hyundai i20 Magna 1.4 CRDi (Diesel),2014,409999,80000,1,0,0,Second Owner
4336,Hyundai i20 Magna 1.4 CRDi,2014,409999,80000,1,0,0,Second Owner
4337,Maruti 800 AC BSIII,2009,110000,83000,0,0,0,Second Owner
4338,Hyundai Creta 1.6 CRDi SX Option,2016,865000,90000,1,0,0,First Owner
4339,Renault KWID RXT,2016,225000,40000,0,0,0,First Owner

In [11]:
df["owner"].unique()
owner = {
    "First Owner": 0,
    "Second Owner": 1,
    "Third Owner": 2,
    "Fourth & Above Owner": 3,
    "Test Drive Car": 4,
}
df["owner"]=df["owner"].map(owner)
df

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,0,0,0,0
1,Maruti Wagon R LXI Minor,2007,135000,50000,0,0,0,0
2,Hyundai Verna 1.6 SX,2012,600000,100000,1,0,0,0
3,Datsun RediGO T Option,2017,250000,46000,0,0,0,0
4,Honda Amaze VX i-DTEC,2014,450000,141000,1,0,0,1
...,...,...,...,...,...,...,...,...
4335,Hyundai i20 Magna 1.4 CRDi (Diesel),2014,409999,80000,1,0,0,1
4336,Hyundai i20 Magna 1.4 CRDi,2014,409999,80000,1,0,0,1
4337,Maruti 800 AC BSIII,2009,110000,83000,0,0,0,1
4338,Hyundai Creta 1.6 CRDi SX Option,2016,865000,90000,1,0,0,0
4339,Renault KWID RXT,2016,225000,40000,0,0,0,0

In [12]:
x=df.drop(columns=["selling_price","name"])
y=df["selling_price"]

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)
from sklearn.linear_model import LinearRegression

In [14]:
lr = LinearRegression()

In [15]:
lr.fit(x_train, y_train)

LinearRegression()

In [16]:
lr.predict(x_test)

array([ 5.51750276e+05,  3.40007462e+05,  5.09636574e+05,  1.34923449e+06,
        4.46292862e+05, -8.95862151e+04,  4.34059814e+04,  1.69689176e+05,
        4.03460943e+05,  8.07217288e+05, -5.30287955e+04,  1.90847019e+05,
        1.45758703e+06,  3.62648082e+05,  5.45749392e+05,  2.24504786e+05,
        6.43103645e+05,  7.64335890e+05,  1.09688589e+06,  3.91841393e+05,
        1.46260688e+06,  3.27951942e+05,  6.16134216e+05,  5.42313655e+05,
        4.98804746e+05, -7.98431172e+03,  5.11222940e+05,  2.09560232e+05,
        3.46365136e+05,  4.33925459e+05,  2.28273444e+05, -9.94396986e+03,
        1.30242202e+05,  1.51026754e+05,  1.03162632e+05,  5.91289269e+05,
        4.66127665e+05,  2.36639802e+05,  1.23472310e+05,  4.42483833e+05,
        1.50124824e+06,  6.19271778e+04,  5.17723390e+04,  5.15133134e+05,
        7.13015134e+05,  5.05625430e+05,  7.50389911e+05,  1.32085130e+05,
        1.69739967e+05, -2.42635183e+05,  5.12819405e+05,  2.34851321e+05,
        5.96886779e+05,  4.60144434e+05,  4.12422689e+05,  1.53846115e+06,
        1.56780408e+06,  6.04060045e+05,  4.23295746e+05,  4.69512612e+05,
        4.40654123e+05,  5.87410865e+05,  8.46501116e+05,  4.69006968e+05,
        1.67246484e+06,  7.49077161e+05,  5.89166281e+05,  1.18254972e+06,
        4.58236182e+05, -2.12103006e+04,  1.61875987e+06, -2.08786273e+05,
        1.33178770e+06,  5.02825453e+05,  4.45868779e+05,  5.45021612e+05,
        6.76953107e+05,  5.03978420e+04,  1.47130841e+06,  4.46316663e+05,
        5.44031989e+05,  8.28529546e+04,  3.73693934e+05,  8.08724573e+04,
        1.06355562e+05,  1.90952584e+04,  3.67398916e+05,  6.39912866e+05,
        4.31378388e+05,  7.31929605e+05,  1.66907990e+06,  6.72408546e+05,
        2.20644966e+05,  5.52266379e+05, -3.32734570e+05,  7.13015134e+05,
        4.85315752e+05,  1.60753476e+06,  1.96020447e+05,  7.15193840e+03,
        4.55972827e+05,  5.16881341e+05,  7.70740817e+05,  2.62546990e+05,
        1.11115744e+06, -2.25642791e+04,  1.30666285e+05, -2.52982038e+05,
        4.19637375e+05,  8.88819191e+05,  4.06845889e+05, -8.52817930e+04,
        3.21353010e+04,  4.13140907e+05,  1.74590165e+06,  3.26350434e+04,
        4.65006075e+05,  6.73568161e+05,  1.76459068e+05,  5.36462572e+05,
        5.55041053e+05,  4.68391021e+05,  5.55176451e+05,  5.40089153e+05,
        3.85707108e+05,  5.89437077e+05,  6.76953107e+05,  2.77198267e+05,
        5.16910891e+05,  8.08372850e+05,  5.35125468e+05,  3.53384256e+05,
        7.02860296e+05,  2.03962721e+05,  6.56643430e+05,  3.72082767e+05,
        1.69859089e+06,  4.27155566e+05,  3.22303641e+05,  2.09560232e+05,
        9.14684314e+05,  6.15124260e+05,  4.10636047e+05,  8.74289556e+05,
        5.18139559e+05,  4.90054677e+05,  6.49336916e+05,  4.85315752e+05,
        5.12344531e+05,  5.45657372e+05,  5.66684839e+05,  4.92085645e+05,
        1.48992561e+06,  3.60154149e+05, -1.79736073e+05,  5.77749484e+05,
        4.25559101e+05,  7.08911970e+05,  2.81310994e+05,  5.52932993e+05,
        5.59036271e+05,  2.23100017e+05,  5.74061997e+02,  1.35228094e+06,
        4.95470591e+05,  7.69504026e+05,  5.07267112e+05,  5.08959585e+05,
        5.69584384e+05,  1.10356608e+05,  4.32328994e+05, -6.10035764e+05,
        2.29869909e+05,  5.17992833e+05,  5.96886779e+05,  3.97388558e+05,
        5.96992886e+05,  4.30065638e+05,  5.57749010e+05,  1.14987264e+06,
        2.43884569e+05,  1.24350557e+05,  1.72244414e+05,  3.67398916e+05,
       -8.40839482e+03,  5.17384107e+05,  3.08288124e+05,  8.46501116e+05,
        2.93627606e+05,  4.14893700e+05,  3.46555916e+04,  1.42901311e+06,
        5.40282687e+05,  5.15031970e+05,  4.52587880e+05,  5.53155045e+05,
        3.55031513e+05,  1.40188275e+06,  1.61130802e+05,  6.89320511e+05,
        5.18231302e+04,  1.47130841e+06,  3.79342236e+05,  4.54659220e+05,
        4.85315752e+05, -4.78553680e+04,  6.04787825e+05,  2.29172402e+05,
        6.35668176e+05, -8.05324487e+04,  2.84603920e+05,  4.52587880e+05,
        4.19910800e+05,  5.50669913e+05,  8.14655920e+05,  5.16204352e+05,
        1.60414982e+06,  5.17723390e+04,  5.83612553e+04,  2.41813229e+05,
        3.69063365e+05,  6.56643430e+05,  3.80938701e+05, -1.91793328e+04,
        5.59036271e+05,  3.78084709e+04,  7.16358852e+05,  6.02706066e+05,
        5.64209698e+05, -7.17420080e+04,  4.25559101e+05,  3.55455596e+05,
        7.23207259e+05,  7.94818296e+05,  1.46260688e+06,  3.13937283e+05,
        8.21302797e+05,  2.81260203e+05,  7.49077161e+05,  6.63413322e+05,
        7.04855516e+04,  5.37130128e+05,  1.57103121e+04,  7.67968005e+05,
        1.46260688e+06,  6.21894153e+05,  2.54180632e+05,  4.39098886e+05,
        2.36639802e+05,  6.16134216e+05,  1.55002076e+06,  1.90952584e+04,
        9.08843134e+05,  5.83612553e+04,  7.38881094e+05,  4.55616922e+05,
        6.39912866e+05,  7.35537376e+05,  4.82354889e+05,  6.96090403e+05,
        6.53792696e+05,  6.01514356e+05,  5.17723390e+04,  1.61880109e+06,
        5.19589298e+05,  1.36333473e+06,  4.23295746e+05, -5.26047124e+04,
        6.12023029e+05,  3.55596821e+05,  4.54851236e+05,  4.42483833e+05,
        1.44471467e+06,  4.52638671e+05,  1.97616912e+05,  2.67022910e+05,
        3.94902569e+05, -1.06015554e+05,  1.90422936e+05,  4.07683765e+05,
        2.54059356e+05,  3.84939746e+05,  5.90116887e+05,  7.31211319e+05,
        4.87049714e+05,  6.02493042e+04,  2.88504969e+05,  3.44401800e+05,
        4.80142325e+05,  1.18141368e+06,  4.60691233e+05,  6.02909163e+05,
        3.99601122e+05,  6.16024075e+05,  1.60932324e+06,  5.47930827e+05,
        4.52587880e+05,  3.22778515e+05,  1.00697162e+05,  6.42274914e+05,
        5.05574639e+05,  5.05574639e+05,  5.13482559e+04,  2.74490310e+05,
        5.87727696e+05,  4.33925459e+05,  3.60447427e+05,  5.13482559e+04,
        1.33946203e+05,  2.29445826e+05,  2.40640847e+05,  6.22206177e+05,
        1.45148456e+06,  4.92780286e+05,  4.83103188e+05,  1.45622349e+06,
        1.56149390e+05,  1.78479616e+05,  1.36920567e+06,  4.35663149e+05,
        7.23169973e+05,  2.29445826e+05,  1.72371790e+06,  3.79342236e+05,
        4.58236182e+05,  5.83612553e+04,  5.19589298e+05,  5.05574639e+05,
        5.51124078e+05,  1.46453766e+06,  6.88123430e+05,  4.45868779e+05,
        4.98127757e+05,  5.37130128e+05,  3.39844471e+05,  1.30242202e+05,
        2.98609017e+05, -1.31498659e+05,  5.62393968e+05,  1.80606592e+05,
        7.23169973e+05,  1.14661030e+05,  4.45817988e+05,  4.36531280e+05,
        1.87714979e+05,  5.51791504e+05,  3.54980721e+05,  1.46260688e+06,
        5.60551136e+05,  6.30736242e+05,  5.63143328e+05,  4.66804655e+05,
        4.41119435e+05,  2.51705063e+05,  7.50389911e+05,  7.56279108e+05,
        8.08724573e+04,  6.34121188e+05,  1.50818603e+06,  2.36690593e+05,
        1.21561682e+06,  2.48583122e+05,  1.23253659e+04, -2.09220223e+05,
       -3.11835428e+04,  4.59357773e+05,  2.43409694e+05,  7.36476727e+04,
        6.29563860e+05,  5.44031989e+05,  6.30736242e+05,  7.09096347e+04,
        2.61773993e+05,  1.26144367e+06,  3.30143797e+05,  1.58815498e+06,
        5.85930227e+04,  1.58220730e+05,  6.02525451e+05,  4.67615203e+05,
        3.08763856e+05,  3.92396727e+05,  3.42608523e+05,  4.66178457e+05,
       -6.42847066e+04,  8.60966759e+04,  5.21745289e+05,  2.32749364e+05,
        5.28006447e+05,  5.26359190e+05,  9.59582370e+04,  5.44031989e+05,
        6.51863277e+05,  4.34059814e+04,  4.13140907e+05,  3.75229509e+05,
        2.67720417e+05,  4.44514800e+05,  5.86115841e+05,  4.72897558e+05,
        5.55176451e+05,  5.89437077e+05,  5.17723390e+04,  4.61727235e+05,
        6.66707835e+05,  3.40319346e+05,  1.57795891e+06,  4.75584996e+05,
        9.94479846e+05,  1.36333473e+06,  2.23150808e+05,  6.82550618e+05,
        6.63413322e+05,  5.42313655e+05,  4.16525853e+05,  7.54307648e+05,
        7.33920852e+05,  3.24092122e+05,  6.30736242e+05,  3.10835195e+05,
        6.22206177e+05,  3.66974833e+05,  3.78169854e+05,  4.70094213e+05,
        6.39912866e+05,  1.52248702e+06,  2.48583122e+05,  3.34671044e+05,
        8.67519663e+05,  1.39032643e+05,  4.58236182e+05,  4.71775967e+05,
       -3.94890104e+04,  3.65751659e+05, -1.07531588e+04,  2.98184934e+05,
        7.66001893e+05,  2.67962904e+05,  7.02860296e+05,  4.99942774e+04,
        1.28740165e+06, -2.89710635e+05,  5.18584521e+05,  5.72333570e+05,
        2.14097042e+05,  4.97683155e+05, -2.58070186e+04,  8.46501116e+05,
        4.64096698e+05,  1.53401550e+06,  3.58081953e+05,  1.41705687e+06,
        3.32174764e+05,  1.90952584e+04,  1.95356777e+05,  4.74887297e+05,
        7.92864118e+04,  5.13259448e+05,  1.43988239e+06,  1.69689176e+05,
        9.95856698e+04,  7.23169973e+05,  5.06049513e+05,  5.47729569e+05,
        4.45817988e+05,  3.96417434e+05,  7.22451755e+05,  5.05574639e+05,
        4.50850190e+05, -4.62589029e+04, -1.19555339e+05,  4.48525945e+05,
        5.02915434e+04,  4.99895719e+05,  3.27477068e+05,  2.94850779e+05,
        1.35156272e+06,  5.58612188e+05,  4.59357773e+05,  4.59832647e+05,
        5.17992833e+05, -3.27191179e+04,  1.00009753e+05,  4.92670614e+05,
        1.16702417e+05,  5.33688041e+04,  9.53183502e+05,  6.43103645e+05,
        3.48210829e+05,  4.26236091e+05,  4.41867733e+05,  1.56149390e+05,
        2.69316883e+05,  4.23770620e+05,  2.02366256e+05,  4.05976883e+05,
        2.90050643e+05,  4.95470591e+05,  4.75605515e+05,  4.97683155e+05,
        2.80087821e+05,  3.08763856e+05,  3.32892982e+05, -4.74312849e+04,
        5.50669913e+05,  1.64985501e+06,  3.69631998e+05,  7.13015134e+05,
        5.58116795e+05,  3.60199897e+04,  3.53435048e+05,  1.47130841e+06,
        6.30736242e+05,  3.36267509e+05,  9.44271420e+05,  6.13951878e+05,
        3.53574327e+05,  4.47480064e+05,  5.07068985e+05,  5.04453048e+05,
        5.52266379e+05,  5.13482559e+04,  7.36850126e+05,  4.59357773e+05,
        8.35496053e+04,  3.29548408e+05,  1.45080757e+06,  5.62695838e+05,
        4.63894583e+05,  4.68158633e+05,  6.23966349e+05,  5.09010376e+05,
        1.96020447e+05,  1.18773757e+05,  3.74168808e+05,  1.61947808e+06,
        1.37436178e+05,  4.06421806e+05,  4.73372432e+05,  5.66917656e+05,
        4.09187042e+05,  4.26680692e+05,  4.13191698e+05,  3.40743429e+05,
        5.15780268e+05, -4.78553680e+04,  4.32328994e+05,  3.87910708e+05,
        5.97846654e+05,  3.39895262e+05,  2.40024748e+05,  1.40391372e+06,
        2.09049562e+05,  4.16525853e+05,  2.28273444e+05,  6.67717745e+05,
        5.96886779e+05,  5.53862844e+05,  1.66294576e+06,  2.60950525e+05,
        1.30789292e+06,  5.75677287e+05,  3.70308988e+05,  1.44740761e+05,
        5.64209698e+05,  4.18789209e+05,  4.85739835e+05,  1.23896393e+05,
        4.78545860e+05,  4.34359962e+05,  3.39228372e+05,  5.48599167e+05,
        3.75765273e+05,  2.17553297e+05,  4.13140907e+05,  1.91306187e+05,
        4.67026623e+05,  4.23295746e+05,  5.49735556e+05,  4.74481104e+05,
        1.61130802e+05,  3.93255313e+05,  1.30653895e+06,  3.48879793e+04,
        5.44031989e+05,  5.47052580e+05,  1.58003111e+06,  5.33688041e+04,
        1.30242202e+05,  4.60144434e+05,  1.74590165e+06,  2.56706993e+05,
        3.79291445e+05, -3.92237621e+03,  5.11667542e+05,  1.64985501e+06,
        5.06049513e+05,  3.86061337e+05,  5.83612553e+04,  5.45072403e+05,
        4.26680692e+05,  4.98804746e+05, -6.65685805e+04,  5.11532144e+05,
        8.09366010e+05,  3.82453566e+05,  5.55547333e+03,  4.71775967e+05,
        1.45525695e+06,  1.54118423e+05,  5.87727696e+05,  7.29781681e+05,
        1.54522630e+06,  5.23367518e+05,  2.68174582e+05,  1.79167025e+05,
        4.23295746e+05,  2.81684286e+05,  6.36333752e+05,  7.57399526e+05,
        8.46501116e+05,  2.36171105e+05,  1.61609314e+06,  5.17723390e+04,
        3.40298635e+05,  2.29496617e+05,  5.06049513e+05,  7.72771785e+05,
        5.94674215e+05,  4.81410089e+05,  4.98663521e+05,  4.84192678e+05,
        1.33178770e+06,  5.45496486e+05, -5.30287955e+04,  4.92085645e+05,
        6.50454519e+05,  3.29548408e+05,  4.40695351e+05,  4.22618757e+05,
        1.09218733e+06,  4.95419800e+05, -1.21441920e+03,  4.13140907e+05,
        2.19512956e+05, -1.12177758e+04,  5.50669913e+05,  1.31288475e+06,
        3.29548408e+05,  4.59357773e+05,  3.20357849e+05,  6.17216118e+05,
        4.27155566e+05,  6.73568161e+05,  2.64143455e+05,  6.80338054e+05,
        3.37631907e+05,  1.96020447e+05,  6.34121188e+05,  5.04453048e+05,
        3.67398916e+05,  5.48740207e+05, -3.94890104e+04,  5.17723390e+04,
        6.25279099e+05,  6.40011976e+05,  6.17196457e+05,  8.17132414e+05,
        3.67398916e+05,  3.82325540e+04,  1.47130841e+06,  6.76953107e+05,
        8.25277272e+05,  5.51114515e+05,  2.95224071e+05,  7.29939866e+05,
        1.39417725e+05,  1.70164050e+05,  5.15052488e+05,  3.77078880e+05,
        3.79342236e+05,  4.85739835e+05,  2.54180632e+05,  4.06845889e+05,
        5.70979591e+05,  1.56149390e+05,  7.59358056e+05,  4.45315786e+05,
        2.15906041e+05,  1.48992561e+06,  4.06371015e+05, -8.17200116e+03,
        4.54184345e+05,  5.57439806e+05,  8.90067479e+04, -5.30287955e+04,
       -3.32734570e+05,  5.15698708e+05,  3.00639985e+05,  9.79892048e+04,
        1.42939596e+06,  6.36333752e+05,  6.68527367e+05,  1.34551104e+06,
        7.19785027e+05,  3.66924041e+05,  4.63444148e+05,  5.01174208e+05,
        2.09560232e+05,  6.44700110e+05,  1.47130841e+06,  1.50173567e+06,
        3.40137749e+05,  1.74590165e+06,  1.17126500e+05,  4.02890060e+05,
        5.23408747e+05,  6.36333752e+05,  5.55547333e+03,  4.46292862e+05,
        4.39048095e+05,  3.55031513e+05,  5.19589298e+05, -3.43155830e+04,
        5.24711934e+05,  4.83103188e+05,  1.23309099e+06,  4.72897558e+05,
        1.53643018e+06,  5.94623424e+05,  6.22206177e+05,  5.41636665e+05,
        1.66941839e+06, -3.68523630e+04,  2.20866934e+05,  6.16134216e+05,
        4.19910800e+05,  1.16884014e+05,  3.31902197e+05,  2.23150808e+05,
        6.67307432e+05,  6.56643430e+05,  1.30717077e+05,  7.26942225e+05,
       -3.41100928e+05,  8.17132414e+05,  1.90952584e+04,  1.68239189e+05,
        1.76883151e+05,  1.74590165e+06,  5.53145483e+05,  5.12819405e+05,
        1.41137016e+06,  4.14788163e+05,  7.24482723e+05,  1.35839713e+05,
        2.09560232e+05,  4.27832556e+05,  6.08308169e+05,  1.47166934e+05,
        3.17099404e+05,  2.90050643e+05,  6.39919636e+05,  6.70183215e+05,
        7.02860296e+05, -1.50635954e+05,  3.68520507e+05,  7.88519091e+04,
        4.33925459e+05,  5.14374642e+05,  4.69006968e+05,  1.50124824e+06,
        4.19961591e+05,  3.22354432e+05,  8.09308686e+05,  5.84519376e+05,
       -8.99860504e+03,  6.77377191e+05,  6.43103645e+05,  5.86115841e+05,
        3.80509575e+04,  3.27477068e+05,  1.52201049e+06,  6.10426564e+05,
        7.72730557e+05,  2.93011506e+05,  2.38711141e+05, -2.43969500e+05,
        1.57745856e+05,  3.89305058e+05,  5.05574639e+05,  2.95274862e+05,
        1.78448807e+05,  1.90952584e+04, -3.13362610e+04,  6.07041618e+05,
        1.50975963e+05, -6.69926636e+04,  7.52462108e+05,  5.02189692e+05,
        5.97541101e+04,  2.51291079e+05,  1.37394459e+06,  5.55176451e+05,
        3.87284510e+05,  3.10552337e+05,  7.50020952e+05,  6.71006053e+04,
        2.83173442e+05,  1.71999446e+06,  1.76459068e+05,  5.55186013e+05,
        7.23169973e+05,  5.49719308e+05,  2.13414061e+05,  7.72771785e+05,
        6.76953107e+05,  5.04453048e+05,  3.75765273e+05, -7.17420080e+04,
        3.98479531e+05,  5.35584134e+05,  6.10426564e+05,  3.54354523e+05,
        5.45061983e+05,  4.52638671e+05,  1.34293718e+05,  4.95932365e+05,
        3.86112128e+05,  3.01569880e+05,  7.30757223e+05,  3.53384256e+05,
        7.67968005e+05,  1.44264587e+06,  1.44742263e+06, -2.34447776e+04,
        7.09096347e+04,  5.84519376e+05,  3.77078880e+05,  1.60255335e+06,
        5.51791504e+05,  3.62841587e+05, -5.93746049e+04,  3.75765273e+05,
        5.61433722e+05,  3.26350434e+04,  5.69457665e+04,  3.22061154e+05,
        6.49873537e+05,  5.43900021e+05,  5.41462860e+05,  4.88649907e+05,
        4.21941767e+05,  6.42858575e+05,  5.15729477e+05,  3.87657802e+05,
        5.23408747e+05,  7.02860296e+05,  8.40253366e+04,  1.49803581e+05,
        6.30059253e+05,  1.56200182e+05,  2.85523396e+05,  5.04693199e+05,
       -9.76491961e+04,  5.13698510e+05,  1.50975963e+05,  3.36318300e+05])

In [17]:
lr.predict(x_train)

array([ 440695.35147886,  360154.148911  , 1406621.67358081, ...,
        315584.53939262,  264375.84275903, 1602553.35213296],
      shape=(3472,))

In [18]:
df.to_csv("used_car_cleaned.csv",index=False)